# Generated by Django 2.2.10 on 2020-12-22 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oneid_meta', '0080_auto_20201222_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScimApp',
            fields=[
                ('app_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oneid_meta.APP')),
                ('refresh_url', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='地址')),
                ('inteval', models.SmallIntegerField(default=5, verbose_name='间隔')),
            ],
            options={
                'abstract': False,
            },
            bases=('oneid_meta.app',),
        ),
    ]
